FROM centos:7

LABEL maintainer="HongX <hx666y@163.com>"

RUN CONFIG="\
	--prefix=/usr/local/nginx \
	--user=www \
	--group=www \
	--with-http_stub_status_module \
	--with-http_ssl_module \
" \
&& groupadd www \
&& useradd -s /sbin/nologin -g www www \
&& yum install -y gcc gcc-c++ make openssl-devel pcre-devel wget net-tools iproute curl \
&& yum clean all \
&& rm -rf /var/cache/yum/* \
&& cd /usr/local/src && wget http://nginx.org/download/nginx-1.15.5.tar.gz \
&& tar xf nginx-1.15.5.tar.gz && cd nginx-1.15.5 \
&& ./configure ${CONFIG} \
&& make -j2 \
&& make install \
&& rm -rf /usr/local/nginx/html/* \
&& echo "ok" >> /usr/local/nginx/html/status.html \
&& cd / && rm -rf /usr/local/src/nginx-* \
&& mkdir -pv /usr/local/nginx/conf/vhost \
&& ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV PATH $PATH:/usr/local/nginx/sbin
COPY nginx.conf /usr/local/nginx/conf/nginx.conf
WORKDIR /usr/local/nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
