FROM centos:7

LABEL maintainer="HongX <hx666y@163.com>"
#ENV JDK_VERSION 8u211
ENV TOMCAT_VERSION 8.5.42

RUN yum install java-1.8.0-openjdk wget unzip iproute net-tools -y \
&& yum clean all \
&& rm -rf /var/cache/yum/* \
&& wget http://mirrors.tuna.tsinghua.edu.cn/apache/tomcat/tomcat-8/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz \
&& groupadd tomcat \
&& useradd -g tomcat tomcat \
&& tar xf apache-tomcat-${TOMCAT_VERSION}.tar.gz \
&& mv apache-tomcat-${TOMCAT_VERSION} /usr/local/tomcat \
&& chown -R tomcat.tomcat /usr/local/tomcat \
&& cd / && rm -rf /usr/local/src/* && rm -rf /usr/local/tomcat/webapps/* \
&& ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV PATH $PATH:/usr/local/tomcat/bin
WORKDIR /usr/local/tomcat
EXPOSE 8080
CMD ["catalina.sh","run"]
